### ISSUE TITLE
Hi Greate Tool. How to fix this issue, xml file not rendering.

### ISSUE THREAD

**Issue by nAkhmedov** [martin-stone/hsv-alpha-color-picker-android#20]
java.lang.NoClassDefFoundError: com/rarepebble/colorpicker/R$styleable
    at com.rarepebble.colorpicker.ColorPreference.<init>(ColorPreference.java:47)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at android.preference.GenericInflater.createItem(GenericInflater.java:385)
    at android.preference.GenericInflater.createItemFromTag(GenericInflater.java:432)
    at android.preference.GenericInflater.rInflate(GenericInflater.java:483)
    at android.preference.GenericInflater.rInflate(GenericInflater.java:495)
    at android.preference.GenericInflater.inflate(GenericInflater.java:327)
    at android.preference.Preference_Delegate.inflatePreference(Preference_Delegate.java:60)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:220)
    at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:426)
    at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:510)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:498)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:888)
    at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:498)
    at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:72)
    at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:610)
    at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:607)
    at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:362)
    at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:607)
    at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:629)
    at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:652)
    at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:80)
    at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:594)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
    at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:589)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:320)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:310)
    at com.intellij.util.ui.update.MergingUpdateQueue$2.run(MergingUpdateQueue.java:254)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:269)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:227)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:217)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)

**Comment by nAkhmedov** [comment]
![image](https://cloud.githubusercontent.com/assets/8067423/14813434/18455ff8-0bbb-11e6-876a-9a3ff4a90b3d.png)

**Comment by martin-stone** [comment]
I'll need more information to be able to help. I'm seeing the preference preview without errors for the demo app. This is in Android Studio 2.0. (I notice you're using 1.5.)

Have you set the dependency in your build.gradle? Does your app compile and run?

**Comment by nAkhmedov** [comment]
Yes, it compiles and runs without problem. The problem is that it is not rendering.

**Comment by martin-stone** [comment]
Well, I can't reproduce it here, but other projects have seen similar problems:

https://github.com/search?q=NoClassDefFoundError+R%24styleable+preview&type=Issues&utf8=%E2%9C%93

Maybe the fixes there will work for you. Other than that, maybe try upgrading to Android Studio 2.0 (which works for me).

If you find a solution, let me know.

**Comment by nAkhmedov** [comment]
It displays well on android 2.0, the problem is on lower than 2.0 of android studio

**Comment by martin-stone** [comment]
Thanks for confirming. I'll consider that a bug in Android Studio rather than in the library, then.
